### ISSUE TITLE
Stuck in the loading screen when you try to edit a non-existing segment

### ISSUE THREAD

**Issue by ReN3xt** [frontiernav/frontiernav-feedback#14]
If you try to edit a non-existent segment you remain stuck in the loading screen.

![non-existent segment](https://user-images.githubusercontent.com/16244142/35466835-efabeb16-0307-11e8-8ab0-f626c86dc076.png)
![loading screen](https://user-images.githubusercontent.com/16244142/35466836-f114dc2e-0307-11e8-9f3a-783a2c427ed8.png)

**Comment by jahed** [comment]
I'm planning to remove the "Edit Controls" options from the map since it's too low-level for most users and can break easily. Are you using it for anything?

**Comment by ReN3xt** [comment]
Actually no, and I agree with you that it can break easily.

**Comment by jahed** [comment]
This was fixed anyway as a consequence of a different bug fix. 👍
