### ISSUE TITLE
Add more languages

### ISSUE THREAD

**Issue by ReN3xt** [frontiernav/frontiernav-feedback#2]
Hi @jahed,
sorry for my English, I'm Italian.
Your project is **absolutely awesome** and **really useful**, so why not extend it by adding multiple languages?
I would take care, if possible, of the Italian translation. It would be a privilege to help you in this project.

keep it up!

**Comment by jahed** [comment]
Multiple language support has been asked for previously. I'm working on exporting the data out so that it's easier to get things translated and switch-able. Probably will add them to this repo and accept pull requests when it gets to that point.

**Comment by Hex7CD** [comment]
That repo now exists. Right here: https://github.com/frontiernav/frontiernav-i18n

**Comment by jahed** [comment]
Going to close this ticket since it's a long-running work in progress. Feel free to open more specific issues related to it.
